escuela/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from teatroescuela.views import *
#example
urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('teatroescuela.urls'))
]

teatroescuela/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views

app_name = 'teatroescuela'

urlpatterns = [
    path('', views.TeatroEscuela.as_view(), name='teatro_escuela'),
    path('nosotres/', views.Nosotres.as_view(), name='nosotres'),
    path('facilitadores/', views.Facilitadores.as_view(), name='facilitadores'),
    path('modelo/', views.Modelo.as_view(), name='modelo'),
    path('contacto/', views.Contacto.as_view(), name='contacto'),
    path('programas/', views.Programas.as_view(), name='programas'),
    path('contacto/registrar/', views.ResgitroView.as_view(), name='registrar'),
    path('extension', views.Extension.as_view(), name='extension'),
    path('investigacion', views.Investigacion.as_view(), name='investigacion'),
]

teatroescuela/models.py
from django.db import models

# Create your models here.

teatroescuela/views.py
from django.shortcuts import render
from django.views.generic import *
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseServerError
from utilidades.views import *
# Create your views here.

class TeatroEscuela(TemplateView):
    template_name = 'index.html'

class Nosotres(TemplateView):
    template_name = 'about.html'

class Modelo(TemplateView):
    template_name = 'modelo.html'

class Contacto(TemplateView):
    template_name = 'contact.html'

class Facilitadores(TemplateView):
    template_name = 'facilitadores.html'

class Programas(TemplateView):
    template_name = 'programas.html'

class Investigacion(TemplateView):
    template_name = 'investigacion.html'

class Extension(TemplateView):
    template_name = 'extension.html'

class ResgitroView(View):

    def post(self, request, *args, **kwargs):

        try:
            status = True
            message = 'Evio de correo'
            error   = 'Envio de correo exitoso'

            # contacto = Contacto()
            # contacto.nombre   = request.POST.get('a-nombre')
            # contacto.correo   = request.POST.get('a-email')
            # contacto.telefono = request.POST.get('a-phone')
            # contacto.mensaje  = request.POST.get('a-mensaje')
            # contacto.save()

            enviar_mail(
                html = True,
                to_email = ['admision@teatroescuela.cl'],
                subject = 'Nueva Consulta',
                message = 'mail/nuevo-admin.html',
                data = {
                    'nombre'   : request.POST.get('a-nombre'),
                    'email'    : request.POST.get('a-email'),
                    'asunto'   : request.POST.get('a-asunto'),
                    'mensaje'  : request.POST.get('a-mensaje'),
                },
            )

            return JsonResponse({
                'status'  : status,
                'message' : message,
                'error'   : error
            })

        except Exception as e:
            print(e)
            return JsonResponse({
                'status'  : status,
                'message' : message,
                'error'   : str(e)
            }, status = 500)

utilidades/views.py
from django.core.mail import EmailMessage
from django.template.loader import get_template, render_to_string
from escuela import settings

def enviar_mail(**kwargs):

    """
        html: boolean
        to_email:
        cc_email
        subject
        attach
        email_message
        data
    """

    status = True
    message = None

    try:
        
        html          = True if 'html' in kwargs else False
        to_email      = kwargs['to_email']
        cc_email      = kwargs['cc_email'] if 'cc_email' in kwargs else []
        subject       = kwargs['subject']
        attach        = kwargs['attach'] if 'attach' in kwargs else False
        email_message = kwargs['message'] if 'message' in kwargs else ''
        data          = kwargs['data'] if 'data' in kwargs else {}

        if html:
            email_message = get_template(email_message).render(data)

        email = EmailMessage(subject, email_message, settings.EMAIL_HOST_USER, to_email, cc=cc_email)
        print(email)

        if attach:
            email.attach_file(attach)

        if html:
            email.content_subtype = 'html'

        email.send()

    except Exception as error:
        print(error)
        status = False
        message = str(error)

    return {
        'status': status,
        'message': message
    }

teatroescuela/templates/about.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="page">
    <nav id="colorlib-main-nav" role="navigation">
      <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle active"><i></i></a>
      <div class="js-fullheight colorlib-table">
        <div class="img" style="background-image: url(/static/assets/images/bg_3.jpg);"></div>
        <div class="colorlib-table-cell js-fullheight">
          <div class="row no-gutters">
            <div class="col-md-12 text-center">
              <h1 class="mb-4"><a href="/" class="logo">Teatro Escuela</a></h1>
              <ul>
                <li><a href="/"><span>Inicio</span></a></li>
                <li class="active"><a href="{% url 'teatroescuela:nosotres' %}"><span>Nosotres</span></a></li>
                <li><a href="{% url 'teatroescuela:modelo' %}"><span>Modelo Educacional</span></a></li>
                <li><a href="{% url 'teatroescuela:facilitadores' %}"><span>Facilitadores</span></a></li>
                <li><a href="{% url 'teatroescuela:programas' %}"><span>Programas Formativos</span></a></li>
                <li><a href="{% url 'teatroescuela:extension' %}"><span>Extensión</span></a></li>
                <li><a href="{% url 'teatroescuela:investigacion' %}"><span>Investigación</span></a></li>
                <li><a href="{% url 'teatroescuela:contacto' %}"><span>Contáctanos</span></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <div id="colorlib-page">
      <header>
      	<div class="container">
	        <div class="colorlib-navbar-brand">
	          <a class="colorlib-logo" href="/">Teatro Escuela</a>
	        </div>
	        <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
        </div>
      </header>

      <section class="hero-wrap js-fullheight" style="background-image: url(/static/assets/images/bg_33.jpg);">
      	<div class="overlay"></div>
	      <div class="container-fluid px-0">
	        <div class="row no-gutters text js-fullheight align-items-end justify-content-center" data-scrollax-parent="true">
	          <div class="col-md-12 ftco-animate text-center">
	            <p class="breadcrumbs"><span class="mr-2"><a href="/">Inicio</a></span> <span>Nosotres</span></p>
	            <h1 class="bread">Nosotres</h1>
	          </div>
	        </div>
	      </div>
      </section>

	    <section class="ftco-section ftco-no-pt ftco-no-pb ftco-about ftco-counter">
	    	<div class="container">
		    	<div class="row no-gutters d-flex">
	    			<div class="col-md-12 col-lg-6 d-flex align-items-stretch">
	    				<div class="img-about img d-flex align-items-stretch">
		    				<div class="img d-flex align-self-stretch align-items-center" style="background-image:url(/static/assets/images/about.jpg);">
		    				</div>
	    				</div>
	    			</div>
	    			<div class="col-md-12 col-lg-6 pl-lg-5 py-5 d-flex align-items-center">
	    				<div class="p-0 px-lg-5 p-lg-0">
		    				<div class="row justify-content-start pb-3">
				          <div class="col-md-12 heading-section ftco-animate">
				          	<span class="subheading">Bienvenides</span>
				            <h2 class="mb-4">Centro de Experimentación Teatral.</h2>
				            <p style="text-align:justify">Centro de investigación, aprendizaje y enseñanzas dedicado a la formación de artistas escénicos, que facilita experiencias sensibles significativas
                      para el aprendizaje desde el autoconocimiento.</p></br>
                    <p style="text-align:justify">Es un espacio humano resguardado y contenido que promueve el principio de igualdad e inclusión comprendiendo al su participante en su máxima integridad.</p>
				          </div>
				        </div>
				        <div class="row">
				        	<div class="col-md-6">
				        		<div class="media block-6 services d-block ftco-animate">
				              <div class="icon"><span class="flaticon-idea"></span></div>
				              <div class="media-body">
				                <h3 class="heading mb-3">Objetivo</h3>
				                <p style="text-align:justify">Ser un centro destacado por la excelencia de sus programas de formación, con un enfoque innovador que no se limita sólo a la práctica dramática sino el descubrimiento de nuevos
                          lenguajes escénicos, en base a la autoría.</p>
                        <p style="text-align:justify">Crear una metodología basada en las
                        necesidades de les estudiantes</p>
                        <p style="text-align:justify">Generar un espacio amable y estimulante para que el estudiante se disponga de manera exploratoria al conocimiento.</p>
				              </div>
				            </div>
				        	</div>
				        	<div class="col-md-6">
				        		<div class="media block-6 services d-block ftco-animate">
				              <div class="icon"><span class="flaticon-idea"></span></div>
				              <div class="media-body">
				                <h3 class="heading mb-3">Por qué lo hacemos?</h3>
				                <p style="text-align:justify">Creemos en una educación alternativa, experimental y centrada en la necesidad de les estudiantes</p>
                        <p style="text-align:justify">Propiciar experiencias formativas transformadoras que conduzcan a la autonomía creativa y desarrollen en nuestros egresados un espíritu investigativo y de constante búsqueda.</p>
				              </div>
				            </div>
				        	</div>
				        </div>
			          <div class="counter-wrap mb-0 ftco-animate d-flex mt-md-3">
		              <div class="text p-4 pr-5 bg-primary">
		              	<p class="mb-0">
			                <span class="number" data-number="30">0</span>
			                <span>Estudiantes</span>
		                </p>
                  </div>
		          </div>
              <div class="counter-wrap mb-0 ftco-animate d-flex mt-md-3">
                <div class="text p-4 pr-5 bg-primary">
                  <p class="mb-0">
                    <span class="number" data-number="2">0</span>
                    <span>Jornadas: </br>Diurno/Vespertino</span>
                  </p>
                </div>
              </div>
              <div class="counter-wrap mb-0 ftco-animate d-flex mt-md-3">
                <div class="text p-4 pr-5 bg-primary">
                  <p class="mb-0">
                    <span class="number" data-number="2">0</span>
                    <span>Cursos: </br>Primero y Segundo</span>
                  </p>
                </div>
              </div>
          </div>
	        </div>
	      </div>
	    </section>

      <footer class="ftco-footer ftco-section img">
	    	<div class="overlay"></div>
	      <div class="container">
	        <div class="row mb-5">
	          <div class="col-lg-3">
	            <div class="ftco-footer-widget mb-4">
	              <h2 class="ftco-heading-2 logo"><a href="/">Teatro Escuela</a></h2>
	              <p>Fundado el año 2020, en Santiago de Chile.</p>
	              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                  <!-- <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li> -->
                  <li class="ftco-animate"><a href="https://www.facebook.com/Teatro-Escuela-116154670206496"><span class="icon-facebook"></span></a></li>
                  <li class="ftco-animate"><a href="https://www.instagram.com/teatro.escuela/"><span class="icon-instagram"></span></a></li>
	              </ul>
	            </div>
	          </div>
	          <div class="col-lg-4">
	            <div class="ftco-footer-widget mb-4">
	              <h2 class="ftco-heading-2">Noticias</h2>
	              <div class="block-21 mb-4 d-flex">
	                <a class="blog-img mr-4" style="background-image: url(/static/assets/images/image_1.jpg);"></a>
	                <div class="text">
	                  <h3 class="heading"><a href="#">Admisión y Convalidaciones - 2021</a></h3>
	                  <div class="meta">
	                    <div><a href="#"><span class="icon-calendar"></span> Marzo 24, 2021</a></div>
	                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
	                    <div><a href="#"><span class="icon-chat"></span> 1</a></div>
	                  </div>
	                </div>
	              </div>
	              <!-- <div class="block-21 mb-4 d-flex">
	                <a class="blog-img mr-4" style="background-image: url(/static/assets/images/image_2.jpg);"></a>
	                <div class="text">
	                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
	                  <div class="meta">
	                    <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
	                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
	                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
	                  </div>
	                </div>
	              </div> -->
	            </div>
	          </div>
	          <div class="col-lg-2">
	             <div class="ftco-footer-widget mb-4 ml-md-4">
	              <h2 class="ftco-heading-2">Links</h2>
	              <ul class="list-unstyled">
                  <li><a href="/" class="py-2 d-block">Teatro Escuela</a></li>
	                <li><a href="/" class="py-2 d-block">Mi TeatroEscuela</a></li>
                  <li><a href="https://www.teatrodelantagonista.cl">Teatro del Antagonista</a></li>

	              </ul>
	            </div>
	          </div>
	          <div class="col-lg-3">
	            <div class="ftco-footer-widget mb-4">
	            	<h2 class="ftco-heading-2">¿Tienes alguna consulta?</h2>
	            	<div class="block-23 mb-3">
                  <ul>
                    <li><span class="icon icon-map-marker"></span><span class="text">Agustinas 1817, Santiago, Chile.</span></li>
                   <li><a href="#"><span class="icon icon-phone"></span><span class="text">+56 9 74324328</span></a></li>
                   <li><a href="#"><span class="icon icon-envelope"></span><span class="text">admision@teatroescuela.cl</span></a></li>
		              </ul>
		            </div>
	            </div>
	          </div>
	        </div>
	        <div class="row">
	          <div class="col-md-12 text-center">

	            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
	  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This page is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://www.teatroescuela.cl" target="_blank">Teatro Escuela</a>
	  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
	          </div>
	        </div>
	      </div>
	    </footer>

      <!-- loader -->
      <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

      </div>
</div>


{% endblock content %}

{% block script %}
<script>
$(document).ready(function() {

});
</script>
{% endblock %}

teatroescuela/templates/contact.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="page">
    <nav id="colorlib-main-nav" role="navigation">
      <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle active"><i></i></a>
      <div class="js-fullheight colorlib-table">
        <div class="img" style="background-image: url(/static/assets/images/bg_3.jpg);"></div>
        <div class="colorlib-table-cell js-fullheight">
          <div class="row no-gutters">
            <div class="col-md-12 text-center">
              <h1 class="mb-4"><a href="/" class="logo">Teatro Escuela</a></h1>
              <ul>
                <li><a href="/"><span>Inicio</span></a></li>
                <li><a href="{% url 'teatroescuela:nosotres' %}"><span>Nosotres</span></a></li>
                <li><a href="{% url 'teatroescuela:facilitadores' %}"><span>Facilitadores</span></a></li>
                <li><a href="{% url 'teatroescuela:modelo' %}"><span>Modelo Educacional</span></a></li>
                <li class="active"><a href="{% url 'teatroescuela:contacto' %}"><span>Contáctanos</span></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <div id="colorlib-page">
      <header>
      	<div class="container">
	        <div class="colorlib-navbar-brand">
	          <a class="colorlib-logo" href="/">Centro de Experimentación</a>
	        </div>
	        <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
        </div>
      </header>

      <section class="hero-wrap js-fullheight" style="background-image: url(/static/assets/images/bg_333.jpg);">
      	<div class="overlay"></div>
	      <div class="container-fluid px-0">
	        <div class="row no-gutters text align-items-end js-fullheight justify-content-center" data-scrollax-parent="true">
	          <div class="col-md-12 ftco-animate text-center">
	            <p class="breadcrumbs"><span class="mr-2"><a href="/">Inicio</a></span> <span>Nosotres</span></p>
	            <h1 class="bread">Escríbenos</h1>
	          </div>
	        </div>
	      </div>
      </section>


	    <section class="ftco-section ftco-no-pt ftco-no-pb contact-section">
        <div class="container">
          <div class="row block-9">
						<div class="col-md-5 d-flex order-last contact-info ftco-animate">
							<div class="row d-flex align-items-center">
								<div class="pl-md-5 p-4">
		              <h2 class="mb-4">Contacto</h2>
		              <p><span>Dirección:</span> Agustinas 1817, Santiago.</p>
		              <p><span>Celular:</span> <a href="tel://1234567920">+ 56 9 63940222</a></p>
		              <p><span>Email:</span> <a href="mailto:info@yoursite.com">admision@teatroescuela.cl</a></p>
		              <p><span>Website:</span> <a href="#">www.teatroescuela.cl</a></p>
		            </div>
							</div>
						</div>
            <div class="col-md-6 order-first ftco-animate">
              <form id="f-contact" action="{% url 'teatroescuela:registrar' %}" class="bg-light p-4 p-md-5" role="form" method="post">
                {% csrf_token %}
                <div class="form-group">
                  <input id="admin-nombre" name="a-nombre" type="text" class="form-control" placeholder="Nombre">
                </div>
                <div class="form-group">
                  <input id="admin-email" name="a-email" type="text" class="form-control" placeholder="Email">
                </div>
                <div class="form-group">
                  <input id="admin-asunto" name="a-asunto" type="text" class="form-control" placeholder="Asunto">
                </div>
                <div class="form-group">
                  <textarea name="admin-mensaje" id="a-mensaje" cols="30" rows="7" class="form-control" placeholder="Mensaje"></textarea>
                </div>
                <div class="form-group">
                  <input type="submit" value="Enviar Mensaje" class="btn btn-primary py-3 px-5">
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>

      <!-- <div id="map"> -->
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3329.2960006297803!2d-70.66437698480088!3d-33.4415939807766!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662c5aeb0ddc5a1%3A0x6e15e5b0542ffb34!2sAgustinas%201817%2C%20Santiago%2C%20Regi%C3%B3n%20Metropolitana!5e0!3m2!1ses!2scl!4v1616022320509!5m2!1ses!2scl" width="100%" height="600" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
      <!-- </div> -->

      <footer class="ftco-footer ftco-section img">
	    	<div class="overlay"></div>
	      <div class="container">
	        <div class="row mb-5">
	          <div class="col-lg-3">
	            <div class="ftco-footer-widget mb-4">
	              <h2 class="ftco-heading-2 logo"><a href="/">Teatro Escuela</a></h2>
	              <p>Fundado el año 2020, en Santiago de Chile.</p>
	              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                  <!-- <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li> -->
                  <li class="ftco-animate"><a href="https://www.facebook.com/Teatro-Escuela-116154670206496"><span class="icon-facebook"></span></a></li>
                  <li class="ftco-animate"><a href="https://www.instagram.com/teatro.escuela/"><span class="icon-instagram"></span></a></li>
	              </ul>
	            </div>
	          </div>
	          <div class="col-lg-4">
	            <div class="ftco-footer-widget mb-4">
	              <h2 class="ftco-heading-2">Recent Blog</h2>
	              <div class="block-21 mb-4 d-flex">
	                <a class="blog-img mr-4" style="background-image: url(/static/assets/images/image_1.jpg);"></a>
	                <div class="text">
	                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
	                  <div class="meta">
	                    <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
	                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
	                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
	                  </div>
	                </div>
	              </div>
	              <div class="block-21 mb-4 d-flex">
	                <a class="blog-img mr-4" style="background-image: url(/static/assets/images/image_2.jpg);"></a>
	                <div class="text">
	                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
	                  <div class="meta">
	                    <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
	                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
	                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
	                  </div>
	                </div>
	              </div>
	            </div>
	          </div>
	          <div class="col-lg-2">
	             <div class="ftco-footer-widget mb-4 ml-md-4">
	              <h2 class="ftco-heading-2">Site Links</h2>
	              <ul class="list-unstyled">
                  <li><a href="/" class="py-2 d-block">Inicio</a></li>
	                <li><a href="{% url 'teatroescuela:nosotres' %}" class="py-2 d-block">Nosotres</a></li>
                  <li><a href="{% url 'teatroescuela:facilitadores' %}" class="py-2 d-block">Facilitadores</a></li>
                  <li><a href="{% url 'teatroescuela:modelo' %}" class="py-2 d-block">Modelo Educacional</a></li>
	                <li><a href="{% url 'teatroescuela:contacto' %}" class="py-2 d-block">Contáctanos</a></li>
	              </ul>
	            </div>
	          </div>
	          <div class="col-lg-3">
	            <div class="ftco-footer-widget mb-4">
	            	<h2 class="ftco-heading-2">¿Tienes alguna consulta?</h2>
	            	<div class="block-23 mb-3">
                  <ul>
                    <li><span class="icon icon-map-marker"></span><span class="text">Agustinas 1817, Santiago, Chile.</span></li>
                   <li><a href="#"><span class="icon icon-phone"></span><span class="text">+56 9 63940222</span></a></li>
                   <li><a href="#"><span class="icon icon-envelope"></span><span class="text">admision@teatroescuela.cl</span></a></li>
		              </ul>
		            </div>
	            </div>
	          </div>
	        </div>
	        <div class="row">
	          <div class="col-md-12 text-center">

	            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
	  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
	  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
	          </div>
	        </div>
	      </div>
	    </footer>

      <!-- loader -->
      <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

      </div>
</div>

{% endblock content %}

{% block script %}
<script>
$(document).ready(function() {
    validar_adminision();
});

function validar_adminision() {
  $("#f-contact").validate({
        'rules': {
          'a-nombre': {
              'required': true,
          },
          'a-asunto': {
              'required': true,
          },
          'a-email': {
              'required': true,
              'email': true,
          },
					'a-mensaje': {
							'required': true,
					},
        },
        errorPlacement: function(error, element) {
            element.closest(".form-group").find('.container-error').html('')
            error.appendTo(element.closest(".form-group").find('.container-error'));
        },
        submitHandler: function(form) {
            $("#f-contact").ajaxSubmit({
                dataType: 'json',
                beforeSend: function() {
                  loading({
                      active: true,
                      description: 'Enviado información.'
                  })
                },
                success: function(response) {
                  loading({active: false})

                },
                error: function(data, a, t) {
                    loading({active: false})
                }
            });
        }
    });
}
</script>
{% endblock %}